### PR TITLE
Handle case when Akka streams source fails in preStart

### LINKED ISSUE #184: Akka streams consumer hangs if failure during prestart
Noticed this when the cluster was not in a healthy state.  The exception was logged to stderr, I assume by akka streams.  It was not propagated to the containing application to deal with.

After this the application hung and did not consume any further messages from pulsar.

When we run the stream, we get back a `Control`, but that does not expose any ability to monitor if it completes or fails.

```
org.apache.pulsar.client.api.PulsarClientException$LookupException: Failed to subscribe persistent://tenant1/test/topic with 64 partitions
Namespace bundle for topic (persistent://tenant1/test/topic-partition-1) not served by this instance. Please redo the lookup. Request is denied: namespace=tenant1/test
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:677)
	at org.apache.pulsar.client.impl.ConsumerBuilderImpl.subscribe(ConsumerBuilderImpl.java:99)
	at com.sksamuel.pulsar4s.DefaultPulsarClient.consumer(PulsarClient.scala:190)
	at com.zendesk.pulsar.test.pulsar.PulsarConsumer.makeConsumer(PulsarConsumer.scala:65)
	at com.zendesk.pulsar.test.pulsar.PulsarConsumer.$anonfun$run$3(PulsarConsumer.scala:24)
	at com.sksamuel.pulsar4s.akka.streams.PulsarSourceGraphStage$$anon$1.preStart(PulsarSourceGraphStage.scala:80)
	at akka.stream.impl.fusing.GraphInterpreter.init(GraphInterpreter.scala:292)
	at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:575)
	at akka.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:682)
	at akka.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:731)
	at akka.actor.Actor.aroundPreStart(Actor.scala:550)
	at akka.actor.Actor.aroundPreStart$(Actor.scala:550)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPreStart(ActorGraphInterpreter.scala:671)
	at akka.actor.ActorCell.create(ActorCell.scala:678)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:549)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:571)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:293)
	at akka.dispatch.Mailbox.run(Mailbox.scala:228)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

### PR DESCRIPTION
**Pull request by gmethvin**
Fixes #184

### CODE REVIEW

File: pulsar4s-akka-streams/src/main/scala/com/sksamuel/pulsar4s/akka/streams/PulsarSourceGraphStage.scala [hunk 1]
```diff
@@ -100,7 +109,7 @@ class PulsarSourceGraphStage[T](create: () => Consumer[T], seek: Option[MessageI
 
       override def shutdown()(implicit ec: ExecutionContext): Future[Done] = {
         completeStage()
-        consumer.closeAsync.map(_ => Done)
+        consumerOpt.fold(Future.successful(Done))(_.closeAsync.map(_ => Done))
```
Comment (gmethvin) [inline pulsar4s-akka-streams/src/main/scala/com/sksamuel/pulsar4s/akka/streams/PulsarSourceGraphStage.scala:112]: This is actually the main issue I noticed. If the consumer is not initialized yet, this will fail, and there are some situations where you might end up calling `shutdown()` during cleanup if the source fails.

**Comment by gmethvin** [comment]
@sksamuel Take a look and let me know what you think. I encountered an issue similar to the original ticket and believe this will fix it. Feel free to cut a release if it looks good.

**Review by sksamuel — APPROVED** [review]
